"""Constants for the MeteoChile Forecast integration."""

DOMAIN = "meteochile_forecast"

CONF_CITY_ID = "city_id"
CONF_CITY_NAME = "city_name"

DEFAULT_SCAN_INTERVAL = 3600  # 1 hour is appropriate for weather forecasts

API_URL = "https://archivos.meteochile.gob.cl/portaldmc/meteochile/js/pronostico.js"

CITIES = {
    "visviri": "Visviri",
    "arica": "Arica",
    "putre": "Putre",
    "colchane": "Colchane",
    "iquique": "Iquique",
    "pica": "Pica",
    "ollague": "Ollagüe",
    "tocopilla": "Tocopilla",
    "calama": "Calama",
    "snpedro": "San Pedro",
    "mejillones": "Mejillones",
    "antofagasta": "Antofagasta",
    "taltal": "Taltal",
    "salvador": "El Salvador",
    "chanaral": "Chañaral",
    "caldera": "Caldera",
    "copiapo": "Copiapó",
    "huasco": "Huasco",
    "freirina": "Freirina",
    "vallenar": "Vallenar",
    "serena": "La Serena/Coquimbo",
    "vicuna": "Vicuña",
    "ovalle": "Ovalle",
    "combarbala": "Combarbalá",
    "illapel": "Illapel",
    "vilos": "Los Vilos",
    "ligua": "La Ligua",
    "papudo": "Papudo/Zapallar",
    "snfelipe": "San Felipe",
    "andes": "Los Andes",
    "calera": "La Calera/Quillota",
    "vdelmar": "Viña del Mar",
    "valpo": "Valparaíso",
    "olmue": "Villa Alemana/Quilpué",
    "casablanca": "Casablanca",
    "algarrobo": "Algarrobo",
    "snantonio": "San Antonio/Cartagena",
    "snantonioi": "San Antonio Interior",
    "colina": "Colina",
    "stgoc": "Santiago Sector Centro",
    "stgon": "Santiago Sector Norte",
    "stgoo": "Santiago Sector Oriente",
    "stgos": "Santiago Sector Sur",
    "stgop": "Santiago Sector Poniente",
    "curacavi": "Curacaví",
    "melipilla": "Melipilla",
    "snjosemaipo": "San José de Maipo",
    "pichilemu": "Pichilemu",
    "rancagua": "Rancagua",
    "rengo": "Rengo",
    "snfernando": "San Fernando",
    "stacruz": "Santa Cruz",
    "curico": "Curicó",
    "molina": "Molina",
    "constitucion": "Constitución",
    "talca": "Talca",
    "linares": "Linares",
    "cauquenes": "Cauquenes",
    "parral": "Parral",
    "cobquecura": "Cobquecura",
    "sancarlos": "San Carlos",
    "chillan": "Chillán",
    "concepcion": "Concepción",
    "talcahuano": "Talcahuano",
    "lota": "Lota",
    "lebu": "Lebu",
    "angeles": "Los Ángeles",
    "angol": "Angol",
    "temuco": "Temuco",
    "psaavedra": "Puerto Saavedra",
    "villarica": "Villarrica/Pucón",
    "panguipulli": "Panguipulli",
    "valdivia": "Valdivia",
    "riobueno": "Río Bueno",
    "union": "La Unión",
    "ranco": "Lago Ranco",
    "osorno": "Osorno",
    "pmontt": "Puerto Montt",
    "cochamo": "Cochamó",
    "ancud": "Ancud",
    "castro": "Castro",
    "chaiten": "Chaitén",
    "quellon": "Quellón",
    "futaleufu": "Futaleufú",
    "melinka": "Melinka",
    "lagoverde": "Lago Verde",
    "aysen": "Puerto Aysén",
    "cisnes": "Puerto Cisnes",
    "coyhaique": "Coyhaique",
    "balmaceda": "Balmaceda",
    "pibanez": "Puerto Ingeniero Ibáñez",
    "chchico": "Chile Chico",
    "cochrane": "Cochrane",
    "tortel": "Caleta Tortel",
    "ohiggins": "Villa O'Higgins",
    "torres": "Torres del Paine",
    "natales": "Puerto Natales",
    "parenas": "Punta Arenas",
    "porvenir": "Porvenir",
    "pwilliams": "Puerto Williams",
    "rapanui": "Isla de Pascua",
    "jfernandez": "Archipiélago Juan Fernández",
    "antartica": "Península Antártica",
}
